### PR TITLE
Add Sync HTTP GET Request

### PR DESCRIPTION
**Pull request by Lacoi**

### CODE REVIEW

**Comment by Pelayori** [comment]
I'm not against adding Sync HTTP requests, but can I get a use case? 
Doing sync http requests in the main thread will make the server hang for as long as it takes, if it times out it will be a problem.

**Comment by Lethalinjectionx** [comment]
I would agree with @Pelayori on this.
Around 3-5 seconds delay on the main thread in ASA boots all players from the server.

**Review by Pelayori — APPROVED** [review]

**Comment by Lethalinjectionx** [comment]
@Pelayori
Should we have a brief added to this stating it is not recommended for use on the main game thread?

**Comment by Pelayori** [comment]
> @Pelayori Should we have a brief added to this stating it is not recommended for use on the main game thread?

Won't hurt, yes. avoids people using it for the first time mistaking it for the Async ones

**Comment by Lethalinjectionx** [comment]
@Lacoi 
 Please update your brief to the following.
 
 "* \brief Creates an sync GET Request that should NOT be called from the main game thread to avoid player timeout issues"
 
 Once that is updated, we can approve and merge.

**Review by Lethalinjectionx — APPROVED** [review]
Looks good

**Pull request merged**
